/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BookCard: typeof import('./src/components/BookCard.vue')['default']
    BookForm: typeof import('./src/components/BookForm.vue')['default']
    BookInfo: typeof import('./src/components/BookInfo.vue')['default']
    LazyLoad: typeof import('./src/components/LazyLoad.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
